# Generated by Django 2.1.5 on 2019-01-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='submissions_count',
            field=models.IntegerField(default=0, verbose_name='Submissions count'),
        ),
    ]
