# Generated by Django 2.1.5 on 2019-01-30 15:29

from django.db import migrations, models
import get_data_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0002_auto_20190128_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='data_file',
            field=models.FileField(upload_to=get_data_form.models.data_file_name, verbose_name='File with data'),
        ),
    ]
