# Generated by Django 2.1.5 on 2019-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0008_result_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='filename',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
