# Generated by Django 2.1.5 on 2019-03-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0009_submission_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result_sol',
            new_name='result_csv',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='stats_rtk',
            new_name='result_pdf',
        ),
    ]
