# Generated by Django 2.1.5 on 2019-03-17 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0010_auto_20190317_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AUTO', max_length=512, unique=True, verbose_name='Antenna ID')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='antenna',
            field=models.CharField(default='AUTO', max_length=512, verbose_name='Antenna ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='filename',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
