# Generated by Django 2.1.5 on 2019-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0011_auto_20190317_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_csv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
