# Generated by Django 2.1.7 on 2019-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_form', '0012_auto_20190320_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='send_email_flag',
            field=models.BooleanField(default=False),
        ),
    ]
